services:
  # Backend service
  - type: web
    name: stattact-backend
    runtime: python
    rootDir: backend  # Add this line
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FOOTBALL_API_KEY
        sync: false
      - key: PORT
        value: 10000

  # Frontend service (if applicable)
  - type: web
    name: stattact-frontend
    runtime: nodejs
    rootDir: frontend  # Add this line
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://stattact-backend.onrender.com
