services:
  # Backend service
  - type: web
    name: stattact-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FOOTBALL_API_KEY
        sync: false
      - key: PORT
        value: 10000

  # Frontend service
  - type: web
    name: stattact-frontend
    runtime: nodejs
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://stattact-backend.onrender.com